import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
    await page.goto('https://app.thetestingacademy.com/playwright/ttacart/');
    await page.locator('[data-test="username"]').click();
    await page.locator('[data-test="username"]').click();
    await page.locator('[data-test="username"]').fill('sumit');
    await page.locator('[data-test="password"]').click();
    await page.locator('[data-test="password"]').fill('abc1234');
    await page.locator('[data-test="login-button"]').click();
    await page.locator('[data-test="error"]').click();
    await expect(page.locator('[data-test="error"]')).toContainText('Epic sadface: Username and password do not match any user in this service');
    await expect(page.locator('[data-test="error"]')).toContainText('Epic sadface: Username and password do not match any user in this service');
    await expect(page.locator('[data-test="error"]')).toMatchAriaSnapshot(`- alert: "Epic sadface: Username and password do not match any user in this service"`);
    await page.locator('[data-test="error"]').click();
    await expect(page.getByRole('heading', { name: 'TTACart' })).toBeVisible();
    await page.locator('[data-test="login-credentials"]').click();
    await page.locator('[data-test="login-credentials"]').click();
    await page.locator('[data-test="username"]').click();
    await page.locator('[data-test="username"]').fill('standard_user');
    await page.locator('[data-test="password"]').click();
    await page.locator('[data-test="password"]').fill('tta_secret');
    await page.locator('[data-test="login-button"]').click();
    await page.getByRole('link').filter({ hasText: 'test.all()' }).click();
    await page.locator('[data-test="inventory-container"] path').click();
    await expect(page.getByRole('article').filter({ hasText: 'TTA Bike LightA red light isn' }).locator('[data-test="item-img-link"]')).toBeVisible();
    await expect(page.getByRole('article').filter({ hasText: 'TTA Bolt T-ShirtGet your' }).locator('[data-test="item-img-link"]')).toBeVisible();
    await expect(page.getByRole('article').filter({ hasText: 'TTA Bolt T-ShirtGet your' }).locator('[data-test="item-img-link"]')).toBeVisible();
    await page.getByRole('link').filter({ hasText: 'test.all()' }).click();
    await page.getByRole('article').filter({ hasText: 'TTA Fleece JacketIt\'s not' }).locator('[data-test="item-img-link"]').click();
    await expect(page.getByRole('link').filter({ hasText: 'JR' })).toBeVisible();
    await expect(page.getByRole('article').filter({ hasText: 'TTA Practice Backpackcarry.' }).locator('[data-test="item-img-link"]')).toBeVisible();
    await expect(page.locator('[data-test="title"]')).toBeVisible();
});
